_wandb:
    value:
        cli_version: 0.19.7.dev1
        m: []
        python_version: 3.10.3
        t:
            "1":
                - 2
                - 3
                - 12
                - 49
                - 55
            "2":
                - 2
                - 3
                - 12
                - 49
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.10.3
            "5": 0.19.7.dev1
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7.dev1
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 64
hidden_layers:
    value: 4
initializer:
    value: RANDOM
learning_rate:
    value: 0.0001
loss:
    value: CROSS
max_epochs:
    value: 10
no_of_hidden_neurons:
    value: 128
optimizer:
    value: NADAM
weight_decay:
    value: 0.0005
