wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_layers:
  value: 4
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 10
no_of_hidden_neurons:
  value: 64
optimizer:
  value: NAG
weight_decay:
  value: 0
