wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_layers:
  value: 4
initializer:
  value: XAVIER
learning_rate:
  value: 0.0001
max_epochs:
  value: 10
no_of_hidden_neurons:
  value: 128
optimizer:
  value: ADAM
weight_decay:
  value: 0.0005
