wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
hidden_layers:
  value: 3
initializer:
  value: RANDOM
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
no_of_hidden_neurons:
  value: 64
optimizer:
  value: ADAM
weight_decay:
  value: 0
