wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
hidden_layers:
  value: 3
initializer:
  value: XAVIER
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
no_of_hidden_neurons:
  value: 32
optimizer:
  value: SGD
weight_decay:
  value: 0.0005
