wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_layers:
  value: 3
initializer:
  value: RANDOM
learning_rate:
  value: 0.001
max_epochs:
  value: 5
no_of_hidden_neurons:
  value: 32
optimizer:
  value: MGD
weight_decay:
  value: 0
