wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
hidden_layers:
  value: 4
initializer:
  value: RANDOM
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
no_of_hidden_neurons:
  value: 128
optimizer:
  value: SGD
weight_decay:
  value: 0.5
