wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
hidden_layers:
  value: 3
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 10
no_of_hidden_neurons:
  value: 32
optimizer:
  value: NADAM
weight_decay:
  value: 0
