wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_layers:
  value: 5
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 10
no_of_hidden_neurons:
  value: 32
optimizer:
  value: RMSPROP
weight_decay:
  value: 0
