wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_layers:
  value: 3
initializer:
  value: RANDOM
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
no_of_hidden_neurons:
  value: 128
optimizer:
  value: NAG
weight_decay:
  value: 0.5
