wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_layers:
  value: 5
initializer:
  value: RANDOM
learning_rate:
  value: 0.001
max_epochs:
  value: 10
no_of_hidden_neurons:
  value: 128
optimizer:
  value: MGD
weight_decay:
  value: 0.0005
