wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
hidden_layers:
  value: 4
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 5
no_of_hidden_neurons:
  value: 128
optimizer:
  value: MGD
weight_decay:
  value: 0.5
