wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_layers:
  value: 3
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 5
no_of_hidden_neurons:
  value: 128
optimizer:
  value: RMSPROP
weight_decay:
  value: 0.0005
