wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
initializer:
  value: RANDOM
learning_rate:
  value: 0.0001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 32
num_layers:
  value: 4
optimizer:
  value: MGD
weight_decay:
  value: 0.0005
