wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
initializer:
  value: XAVIER
learning_rate:
  value: 0.0001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 128
num_layers:
  value: 5
optimizer:
  value: NAG
weight_decay:
  value: 0.0005
