wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
initializer:
  value: RANDOM
learning_rate:
  value: 0.001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 128
num_layers:
  value: 4
optimizer:
  value: SGD
weight_decay:
  value: 0.5
