wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 10
num_hidden_neurons:
  value: 64
num_layers:
  value: 5
optimizer:
  value: NADAM
weight_decay:
  value: 0
