wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
initializer:
  value: XAVIER
learning_rate:
  value: 0.001
max_epochs:
  value: 5
num_hidden_neurons:
  value: 32
num_layers:
  value: 3
optimizer:
  value: MGD
weight_decay:
  value: 0.5
