wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
hidden_layers:
  value: 3
initializer:
  value: random
learning_rate:
  value: 0.0001
max_epochs:
  value: 10
no_of_hidden_neurons:
  value: 64
optimizer:
  value: adam
weight_decay:
  value: 0
